version: '3'

tasks:

  precommit:
      cmds:
        - echo "🚓・Running pre-commit in all files"
        - pre-commit run --all-files
        - echo "Done 🪇"
      silent: true

  build:
    cmds:
      - echo "🏗️・Building the project"
      - go fmt ./...
      - go build -o bin/goodcommit cmd/goodcommit/main.go
      - echo "Done 🪇"
    silent: true
